# -*- coding: utf-8 -*-

USHRT_MAX = 65535

# Command codes
CMD_CONNECT         = 1000
CMD_EXIT            = 1001
CMD_ENABLEDEVICE    = 1002
CMD_DISABLEDEVICE   = 1003
CMD_RESTART         = 1004
CMD_POWEROFF        = 1005
CMD_SLEEP           = 1006
CMD_RESUME          = 1007
CMD_CAPTUREFINGER   = 1009
CMD_TEST_TEMP       = 1011
CMD_CAPTUREIMAGE    = 1012
CMD_REFRESHDATA     = 1013
CMD_REFRESHOPTION   = 1014
CMD_TESTVOICE       = 1017
CMD_VERSION         = 1100
CMD_CHANGE_SPEED    = 1101
CMD_COMMITPWD       = 1102
CMD_CLEARADMIN      = 1103

CMD_DB_RRQ          = 7
CMD_USER_WRQ        = 8
CMD_USERTEMP_RRQ    = 9
CMD_USERTEMP_WRQ    = 10
CMD_OPTIONS_RRQ     = 11
CMD_OPTIONS_WRQ     = 12
CMD_ATTLOG_RRQ      = 13
CMD_CLEAR_DATA      = 14
CMD_CLEAR_ATTLOG    = 15
CMD_DELETE_USER     = 18
CMD_DELETE_USERTEMP = 19
CMD_CLEAR_ADMIN     = 20
CMD_USERGRP_RRQ     = 21
CMD_USERGRP_WRQ     = 22
CMD_USERTZ_RRQ      = 23
CMD_USERTZ_WRQ      = 24
CMD_GRPTZ_RRQ       = 25
CMD_GRPTZ_WRQ       = 26
CMD_TZ_RRQ          = 27
CMD_TZ_WRQ          = 28
CMD_ULG_RRQ         = 29
CMD_ULG_WRQ         = 30
CMD_UNLOCK          = 31
CMD_CLEAR_ACC       = 32
CMD_CLEAR_OPLOG     = 33
CMD_OPLOG_RRQ       = 34
CMD_GET_FREE_SIZES  = 50
CMD_ENABLE_CLOCK    = 57
CMD_STARTVERIFY     = 60
CMD_STARTENROLL     = 61
CMD_CANCELCAPTURE   = 62
CMD_STATE_RRQ       = 64
CMD_WRITE_LCD       = 66
CMD_CLEAR_LCD       = 67
CMD_GET_PINWIDTH    = 69
CMD_SMS_WRQ         = 70
CMD_SMS_RRQ         = 71
CMD_DELETE_SMS      = 72
CMD_UDATA_WRQ       = 73
CMD_DELETE_UDATA    = 74
CMD_DOORSTATE_RRQ   = 75
CMD_WRITE_MIFARE    = 76
CMD_EMPTY_MIFARE    = 78

CMD_GET_TIME        = 201
CMD_SET_TIME        = 202

CMD_REG_EVENT       = 500

# Acknowledge codes
CMD_ACK_OK          = 2000
CMD_ACK_ERROR       = 2001
CMD_ACK_DATA        = 2002
CMD_ACK_RETRY       = 2003
CMD_ACK_REPEAT      = 2004
CMD_ACK_UNAUTH      = 2005
CMD_ACK_UNKNOWN     = 65535

# Event codes
EF_ATTLOG           = 1
EF_FINGER           = 2
EF_ENROLLUSER       = 4
EF_ENROLLFINGER     = 8
EF_BUTTON           = 16
EF_UNLOCK           = 32
EF_DOOR             = 64
EF_ALARM            = 128
EF_HBUSER           = 256
EF_HBFP             = 512
EF_HBFACE           = 1024

# User privilege levels
USER_DEFAULT        = 0
USER_ENROLLER       = 2
USER_MANAGER        = 6
USER_ADMIN          = 14

# Finger constants
FINGER_SUCCESS      = 0
FINGER_FAIL         = 1
FINGER_TIMEOUT      = 2
FINGER_TOOFAST      = 3
FINGER_CANCEL       = 4
FINGER_DUPLICATE    = 5

# Data constants for CMD_DB_RRQ
FC_PC_USERS         = b'\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
